import "@/styles/globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { TailwindIndicator } from "@/components/tailwind-indicator"
import { SiteHeader } from "@/components/site-header"

const inter = Inter({ subsets: ["latin"] })

// import { GeistSans } from "geist/font/sans"
// import { GeistMono } from "geist/font/mono"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            <div className="flex-1">{children}</div>
          </div>
          {/* <Toaster /> */}
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  )
}
